image: python:3.9

stages:
  - build
  - start

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - python startup.py

start:
  stage: start
  script:
    - uvicorn main:app --host