"""settings change to settings

Revision ID: 478fb4dae08e
Revises: 883c87f858a0
Create Date: 2023-11-11 12:06:41.109308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478fb4dae08e'
down_revision: Union[str, None] = '883c87f858a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('preferences', 'settings')
    op.alter_column('roles', 'preferences', new_column_name='settings')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('settings', 'preferences')
    op.alter_column('roles', 'settings', new_column_name='preferences')
    # ### end Alembic commands ###
