"""Hermes 1_4 DB upgrade

Revision ID: 883c87f858a0
Revises: 
Create Date: 2023-11-11 10:55:01.010429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883c87f858a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('users_profile', sa.String, nullable=True))
    op.add_column('users', sa.Column('dark_mode', sa.Integer, nullable=True))
    op.add_column('employees', sa.Column('employee_profiles', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('company_logo', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('navigation_bar_color', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('primary_color', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('primary_color_hover', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('secondary_color', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('secondary_color_hover', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('info_color', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('info_color_hover', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('critical_color', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('critical_color_hover', sa.String, nullable=True))
    op.add_column('preferences', sa.Column('table_color_id', sa.Integer, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'table_color_id')
    op.drop_column('preferences', 'critical_color_hover')
    op.drop_column('preferences', 'critical_color')
    op.drop_column('preferences', 'info_color_hover')
    op.drop_column('preferences', 'info_color')
    op.drop_column('preferences', 'secondary_color_hover')
    op.drop_column('preferences', 'secondary_color')
    op.drop_column('preferences', 'primary_color_hover')
    op.drop_column('preferences', 'primary_color')
    op.drop_column('preferences', 'navigation_bar_color')
    op.drop_column('preferences', 'company_logo')
    op.drop_column('employees', 'employee_profiles')
    op.drop_column('users', 'dark_mode')
    op.drop_column('users', 'users_profile')
    # ### end Alembic commands ###